name: Check the code
on: push
jobs:
    Lint-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: install dependences
              run: npm ci   

            - name: testing lint
              run: npm run lint

            - name: runing test
              run: npm run test
    Deploy:
        runs-on: ubuntu-latest
        needs: Lint-test
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: deploying
              run: echo 'deploying'

            - name: Check the github variables
              run: echo "${{ toJson(github.event) }}""